Train:
  batch_size: 70
  learning_rate: 0.13
  reg: 0
  epochs: 10
  momentum: 0.9
  debug: True

Model:
  type: TwoLayerNet # SoftmaxRegression or TwoLayerNet
  hidden_size: 100 # only applicable for TwolayerNet